apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DB_USER: "postgres"       # Utilisé dans postgres.yml
  DB_NAME: "filrouge"       # Utilisé dans postgres.yml
  DB_HOST: "postgres-service" # Probablement nécessaire pour auth/story
  PORT_AUTH: "4000"              # Port pour auth-service
  PORT_STORY: "5000"       # Port pour story-service
  FRONTEND_ORIGIN: "http://localhost"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  DB_PASSWORD: "monpasswordsecurise" # Utilisé dans postgres.yml
  
  DB_URL: "postgres://postgres:monpasswordsecurise@postgres-service:5432/filrouge"
  
  # Indispensable pour que le service Auth ne plante pas
  JWT_SECRET: "un_super_secret_pour_les_tokens_jwt"
  ADMIN_name: "Example Admin"
  ADMIN_Password: "exampleAdminPass!"
  ADMIN_email: "exampleAdmin@example1.com"
  ADMIN_profileData: "Example Admin Profile Data"